dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc

# Install dependencies needed for docs
addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

# Use conda to install LSDTT and create a virual environment
install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install conda-build
  - cd conda-recipe
  - conda build lsdtopotools -c conda-forge
  - conda create -n lsdtt lsdtopotools -c conda-forge --use-local
  # Needed to run the tests
  - conda install git pip pytest numpy
  # From the rasterio docs
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update -y
  - sudo apt-get install gdal-bin libgdal-dev -y
  - pip install rasterio

# Activate the venv and run a driver
script:
  - source activate lsdtt
  - cd ..
  - cd tests/
  - mkdir results
  - cd fixtures
  - wget https://github.com/LSDtopotools/ExampleTopoDatasets/raw/master/coweeta.bil
  - wget https://github.com/LSDtopotools/ExampleTopoDatasets/raw/master/coweeta.hdr
  - wget https://github.com/LSDtopotools/RegressionData/raw/master/coweeta_output_ASPECT.bil
  - wget https://github.com/LSDtopotools/RegressionData/raw/master/coweeta_output_ASPECT.hdr
  - wget https://github.com/LSDtopotools/RegressionData/raw/master/coweeta_output_CLASS.bil
  - wget https://github.com/LSDtopotools/RegressionData/raw/master/coweeta_output_CLASS.hdr
  - wget https://github.com/LSDtopotools/RegressionData/raw/master/coweeta_output_CURV.bil
  - wget https://github.com/LSDtopotools/RegressionData/raw/master/coweeta_output_CURV.hdr
  - wget https://github.com/LSDtopotools/RegressionData/raw/master/coweeta_output_PLFMCURV.bil
  - wget https://github.com/LSDtopotools/RegressionData/raw/master/coweeta_output_PLFMCURV.hdr
  - wget https://github.com/LSDtopotools/RegressionData/raw/master/coweeta_output_PROFCURV.bil
  - wget https://github.com/LSDtopotools/RegressionData/raw/master/coweeta_output_PROFCURV.hdr
  - wget https://github.com/LSDtopotools/RegressionData/raw/master/coweeta_output_SLOPE.bil
  - wget https://github.com/LSDtopotools/RegressionData/raw/master/coweeta_output_SLOPE.hdr
  - wget https://github.com/LSDtopotools/RegressionData/raw/master/coweeta_output_SMOOTH.bil
  - wget https://github.com/LSDtopotools/RegressionData/raw/master/coweeta_output_SMOOTH.hdr
  - wget https://github.com/LSDtopotools/RegressionData/raw/master/coweeta_output_TANCURV.bil
  - wget https://github.com/LSDtopotools/RegressionData/raw/master/coweeta_output_TANCURV.hdr
  - cd ..
  - lsdtt-basic-metrics fixtures/ coweeta.driver
  - pytest -v

after_success:
  # Build the docs
  - pwd
  - cd ..
  - sh build_docs.sh

# Deploy using travis builtin GitHub Pages support - only for changes to master
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html/
  github_token: $GITHUB_API_KEY
  on:
    branch: travis
